services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - HOME=/root
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=EbookReader;Username=postgres;Password=postgres
      - FileStorage__Type=Local
      - FileStorage__LocalPath=/app/storage
    volumes:
      - ./backend:/src
      - ~/.aspnet/https:/https:ro
      - "${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"
      - backend-storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5174:5173"
    environment:
      - VITE_API_URL=https://localhost:5001
